services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=management-system'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=romansulymka'
    ports:
      - '5432:5432'
