name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: romansulymka
          POSTGRES_DB: management-system

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw clean install
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=romansulymka/course-management-system:v1

      - name: Push Docker image
        run: docker push romansulymka/course-management-system:v1

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco

      - name: Display Code Coverage Report
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: target/site/jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Display Coverage Report Link
        run: |
          RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
          echo "Code Coverage Report: [Download Here]($RELEASE_URL)"


