name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  management-system:
    name: Course management system
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: romansulymka
          POSTGRES_DB: management-system

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run migration and build with Maven
        run: |
          ./mvnw flyway:migrate
          ./mvnw clean install
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=romansulymka/course-management-system:v1 -DskipTests

      - name: Push Docker image
        run: docker push romansulymka/course-management-system:v1

      - name: Set up SSH key
        run: |
          echo ${{ secrets.EC2_PRIVATE_KEY }} > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      - name: Verify SSH host key
        run: |
          ssh-keygen -R ec2-52-3-252-203.compute-1.amazonaws.com
          ssh-keyscan -H ec2-52-3-252-203.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Debug SSH key content
        run: cat ~/.ssh/key.pem

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/key.pem ec2-user@ec2-52-3-252-203.compute-1.amazonaws.com 'bash -s' << 'ENDSSH'
          docker pull romansulymka/course-management-system:v1
          docker-compose down app
          docker-compose up -d
          docker ps
          ENDSSH

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco

      - name: Display Code Coverage Report
        uses: actions/checkout@v2

      - name: Display Coverage Report Link
        run: |
          RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
          echo "Code Coverage Report: [Download Here]($RELEASE_URL)"
